apiVersion: v1
kind: Secret
metadata:
  name:  {{ include "llm-service.fullname" . }}-regcred
  namespace: {{ .Release.Namespace }}
data:
  .dockerconfigjson: {{ .Values.imagePullSecrets.dockerconfigjson }}
type: {{ .Values.imagePullSecrets.type }}