apiVersion: v1
kind: Service
metadata:
  name: {{ include "llm-service.fullname" . }}
  labels:
    {{- include "llm-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if contains "NodePort" .Values.service.type }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "llm-service.selectorLabels" . | nindent 4 }}