apiVersion: v1
kind: ServiceAccount
metadata:
  name:  {{ include "llm-service.fullname" . }}-service-account
  labels:
    {{- include "llm-service.labels" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}